import type { Metadata } from "next";
import Footer from "@/components/footer";
import Header from "@/components/header";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import {Providers} from "./providers";

config.autoAddCss = false;
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
        <main className="grid grid-cols-12">
          <div className="col-span-12 md:col-span-3 lg:col-span-2">
            <Header />
          </div>
          <div className="col-span-12 md:col-span-9 lg:col-span-10">
            {children}
          </div>
        </main>
        </Providers>
      </body>
    </html>
  );
}
