import type { Metadata } from "next";
// import Footer from "@/components/footer";
import Header from "@/components/header";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { Providers } from "./providers";
import { AuthProvider } from "@/context/AuthContext";
import Script from "next/script";
import { Quicksand, Nunito } from "next/font/google";

config.autoAddCss = false;
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
  variable: "--font-quicksand",
});

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  display: "swap",
  variable: "--font-nunito",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${quicksand.variable} ${nunito.variable}`}>
      <body className="bg-default-200 p-4">
        <AuthProvider>
          <Providers>
            <main className="grid grid-cols-12 gap-8">
              <div className="col-span-12 md:col-span-3 lg:col-span-2">
                <div className="bg-white rounded-lg overflow-hidden">
                  <Header />
                </div>
              </div>
              <div className="col-span-12 md:col-span-9 lg:col-span-10">
                <div className="bg-white rounded-lg">{children}</div>
              </div>
            </main>
          </Providers>
        </AuthProvider>
        <Script
          src="https://widgets.api-sports.io/2.0.3/widgets.js"
          type="module"
          crossOrigin="anonymous"
        />
      </body>
    </html>
  );
}
